### ISSUE TITLE
Crashed: com.apple.root.user-initiated-qos

### ISSUE THREAD

**Issue by TomCarey** [inner-active/InneractiveAdSDK-iOS#31] opened 2021-09-06 03:07 UTC
I have the following stack trace causing a significant number of crashes on my app in production.

```
Crashed: com.apple.root.user-initiated-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000630830149530

0  libobjc.A.dylib                0x1aeb8b1c8 objc_msgSend + 8
1  CoreFoundation                 0x199fc745c -[__NSDictionaryM objectForKeyedSubscript:] + 184
2  MyApp                          0x104deb1b0 +[FYBBaseProxy class] + 76 (FYBBaseProxy.m:76)
3  CoreFoundation                 0x19a0ecdec ___forwarding___ + 228
4  CoreFoundation                 0x19a0ef5b0 _CF_forwarding_prep_0 + 96
5  MyApp                          0x104dbea68 __35-[FYBDV360UnitBase createQueryInfo]_block_invoke + 67 (FYBDV360UnitBase.m:67)
6  libdispatch.dylib              0x199cd5a84 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x199cd781c _dispatch_client_callout + 20
8  libdispatch.dylib              0x199ce910c _dispatch_root_queue_drain + 688
9  libdispatch.dylib              0x199ce97d8 _dispatch_worker_thread2 + 112
10 libsystem_pthread.dylib        0x1e5d66768 _pthread_wqthread + 216
11 libsystem_pthread.dylib        0x1e5d6d74c start_wqthread + 8
```

From my podfile.lock:
```
  - Fyber_Marketplace_SDK (7.8.8):
    - Fyber_Marketplace_SDK/IASDKCore (= 7.8.8)
```

These crashes are happening almost entirely on iOS 14.6.0 - 14.7.1 while running in the foreground.

**Comment by 2energycell** [comment] 2022-01-23 16:30
the issue is resolved in newer versions;

**Closed by 2energycell** 2022-01-23 16:30 UTC
